import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PageHero } from "@/components/PageHero";
import { business, hours } from "@/lib/content/site";
import { CtaBand, LocationPanel } from "@/components/public/PublicUI";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return[{slug:"northfield"}]}
export async function generateMetadata({params}:Props):Promise<Metadata>{if((await params).slug!=="northfield")return{};return{title:"Northfield Location",description:`Luxury Barber Lounge at ${business.street}, ${business.city}, New Jersey.`,alternates:{canonical:"/locations/northfield"}}}
export default async function LocationPage({params}:Props){if((await params).slug!=="northfield")notFound();return <><PageHero eyebrow={{en:"Northfield, New Jersey",es:"Northfield, Nueva Jersey"}} title={{en:"The Northfield Lounge",es:"El Salón de Northfield"}} lead={{en:"A reserved chair, complimentary parking, and a calm room built around precision service.",es:"Una silla reservada, estacionamiento gratuito y un espacio creado para servicio preciso."}}/><main className="mx-auto max-w-6xl px-6 pb-28 sm:px-10"><LocationPanel/><section className="mt-12 grid gap-6 md:grid-cols-2"><div className="border border-[var(--color-ink-line)] p-7"><h2 className="font-display text-3xl">Hours</h2><dl className="mt-6 space-y-3">{hours.map((row)=><div key={row.weekday} className="flex justify-between border-b border-[var(--color-ink-line)] pb-3 text-sm"><dt>{row.day.en}</dt><dd className={row.closed?"text-[var(--color-oxblood)]":"text-[var(--color-brass)]"}>{row.closed?"Closed":`${row.open}–${row.close}`}</dd></div>)}</dl></div><div className="border border-[var(--color-ink-line)] p-7"><h2 className="font-display text-3xl">Before you arrive</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-[var(--color-bone-muted)]"><li>Complimentary parking directly outside the suite.</li><li>Arrive five to ten minutes early for a first-visit consultation.</li><li>Bring one or two useful reference images for a significant change.</li><li>Contact the lounge in advance for accessibility accommodations.</li></ul></div></section></main><CtaBand/></>}
