import Link from "next/link";
import { CalendarPlus, ClipboardCheck, Plus, RefreshCw, Settings, UserPlus } from "lucide-react";
import { portalDemo } from "@/lib/content/platform";
import { PortalShell, type PortalRole } from "./PortalShell";
import { ActionCard, DemoModeBanner, MetricGrid, PortalHeader, PortalTable } from "./PortalUI";

function rows<T extends ReadonlyArray<Record<string, string>>>(items: T) { return items as unknown as ReadonlyArray<Record<string, string>>; }

export function PortalDashboard({ role }: { role: PortalRole }) {
  if (role === "client") {
    return <PortalShell role="client"><DemoModeBanner /><PortalHeader eyebrow="Welcome back" title="Your grooming, organized." copy="Rebook, review upcoming appointments, save preferences, and manage communication from one calm place." actions={<Link href="/book" className="inline-flex items-center gap-2 rounded-full bg-[var(--color-brass)] px-5 py-3 text-[10px] tracking-[.18em] uppercase text-[var(--color-ink)]"><CalendarPlus className="h-4 w-4" /> Book</Link>} /><MetricGrid metrics={portalDemo.client.metrics} /><section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-2xl">Appointments</h2><Link href="/client/appointments" className="text-[10px] tracking-[.18em] uppercase text-[var(--color-brass)]">View all</Link></div><PortalTable columns={["Date","Service","Barber","Status","Total"]} rows={rows(portalDemo.client.appointments)} /></section><div className="mt-8 grid gap-4 md:grid-cols-3"><ActionCard title="Rebook your last service" copy="Return to the same service and preferred chair with details preselected." href="/client/rebook" label="Start rebooking" /><ActionCard title="Save your grooming profile" copy="Store preferred guard, fade, beard, product, and reference-image details." href="/client/grooming-profile" label="Update profile" /><ActionCard title="Share feedback" copy="Private feedback reaches management before any optional public review invitation." href="/client/feedback" label="Open feedback" /></div></PortalShell>;
  }
  if (role === "barber") {
    return <PortalShell role="barber"><DemoModeBanner /><PortalHeader eyebrow="Barber workspace" title="Today, at a glance." copy="A focused view of the chair, queue, service revenue, notifications, and provisional statement activity." actions={<Link href="/barber/today" className="inline-flex items-center gap-2 rounded-full bg-[var(--color-brass)] px-5 py-3 text-[10px] tracking-[.18em] uppercase text-[var(--color-ink)]"><ClipboardCheck className="h-4 w-4" /> Open today</Link>} /><MetricGrid metrics={portalDemo.barber.metrics} /><section className="mt-8"><h2 className="font-display mb-4 text-2xl">Next in the chair</h2><PortalTable columns={["Time","Client","Service","Status"]} rows={rows(portalDemo.barber.schedule)} /></section><div className="mt-8 grid gap-4 md:grid-cols-3"><ActionCard title="Portfolio review" copy="Upload work, tag the service and style, and submit it for owner approval." href="/barber/portfolio" label="Manage portfolio" /><ActionCard title="Commission details" copy="Review attribution, rules, tips, adjustments, and the open dispute window." href="/barber/commissions" label="Open statement" /><ActionCard title="Schedule request" copy="Prepare availability, time-off, or blocked-time requests for management review." href="/barber/profile" label="Manage availability" /></div></PortalShell>;
  }
  if (role === "reception") {
    return <PortalShell role="reception"><DemoModeBanner /><PortalHeader eyebrow="Front desk" title="Keep the floor moving." copy="Appointments, arrivals, walk-ins, communication, and assignment controls designed for fast service at the counter." actions={<div className="flex gap-2"><Link href="/reception/check-in" className="inline-flex items-center gap-2 rounded-full border border-[var(--color-ink-line)] px-5 py-3 text-[10px] tracking-[.18em] uppercase"><UserPlus className="h-4 w-4" /> Check in</Link><Link href="/reception/queue" className="inline-flex items-center gap-2 rounded-full bg-[var(--color-brass)] px-5 py-3 text-[10px] tracking-[.18em] uppercase text-[var(--color-ink)]"><Plus className="h-4 w-4" /> Walk-in</Link></div>} /><MetricGrid metrics={portalDemo.reception.metrics} /><section className="mt-8"><h2 className="font-display mb-4 text-2xl">Live queue preview</h2><PortalTable columns={["Token","Service","Preference","Wait","Status"]} rows={rows(portalDemo.reception.queue)} /></section><div className="mt-8 grid gap-4 md:grid-cols-3"><ActionCard title="Appointment search" copy="Find a booking, confirm contact details, and manage arrival state." href="/reception/schedule" label="Search schedule" /><ActionCard title="Customer communication" copy="Prepare approved transactional messages without exposing campaigns or owner settings." href="/reception/messages" label="Open messages" /><ActionCard title="Kiosk controls" copy="Pause check-in, update shop status, and reset the public tablet safely." href="/reception/kiosk" label="Manage kiosk" /></div></PortalShell>;
  }
  return <PortalShell role="admin"><DemoModeBanner /><PortalHeader eyebrow="Executive view" title="One operating picture." copy="A role-aware command center for bookings, clients, barbers, content, automations, reconciliation, and integration health." actions={<div className="flex flex-wrap gap-2"><Link href="/admin/content" className="inline-flex items-center gap-2 rounded-full border border-[var(--color-ink-line)] px-5 py-3 text-[10px] tracking-[.18em] uppercase"><Settings className="h-4 w-4" /> Content</Link><Link href="/admin/operations" className="inline-flex items-center gap-2 rounded-full bg-[var(--color-brass)] px-5 py-3 text-[10px] tracking-[.18em] uppercase text-[var(--color-ink)]"><RefreshCw className="h-4 w-4" /> Operations</Link></div>} /><MetricGrid metrics={portalDemo.admin.metrics} /><section className="mt-8"><h2 className="font-display mb-4 text-2xl">Business activity</h2><PortalTable columns={["Item","Owner","Status","Time"]} rows={rows(portalDemo.admin.activity)} /></section><div className="mt-8 grid gap-4 md:grid-cols-4"><ActionCard title="Square activation" copy="Connect locations, catalog, team members, bookings, payments, and verified webhooks." href="/admin/integrations" label="Integration status" tone="warning" /><ActionCard title="Content readiness" copy="Review curated placeholders, publish states, media, policies, and SEO data." href="/admin/content" label="Open content" /><ActionCard title="Automation center" copy="Configure triggers, timing, templates, consent checks, quiet hours, and delivery logs." href="/admin/automations" label="Review automations" /><ActionCard title="Commission review" copy="Prepare attribution, versioned rules, statements, disputes, and locked periods." href="/admin/commissions" label="Open reconciliation" /></div></PortalShell>;
}
