"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export function AdminBarberEditor({ barber, owner }: { barber: { id:string; name:string; title:string; intro:string; biography:string; specialties:string[]; languages:string[]; squareTeamMemberId:string|null; active:boolean; featured:boolean; status:string }; owner: boolean }) {
  const router=useRouter(); const [name,setName]=useState(barber.name); const [title,setTitle]=useState(barber.title); const [intro,setIntro]=useState(barber.intro); const [bio,setBio]=useState(barber.biography); const [specialties,setSpecialties]=useState(barber.specialties.join("\n")); const [languages,setLanguages]=useState(barber.languages.join(", ")); const [squareId,setSquareId]=useState(barber.squareTeamMemberId??""); const [active,setActive]=useState(barber.active); const [featured,setFeatured]=useState(barber.featured); const [profileStatus,setProfileStatus]=useState(barber.status); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);
  async function save(){setBusy(true);setStatus("Saving barber profile...");const response=await fetch(`/api/admin/barbers/${barber.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:name,professionalTitle:title,shortIntro:intro,biography:bio,specialties:specialties.split("\n").map((v)=>v.trim()).filter(Boolean),languages:languages.split(",").map((v)=>v.trim()).filter(Boolean),active,featured,status:profileStatus,...(owner?{squareTeamMemberId:squareId||null}:{})})});const body=await response.json().catch(()=>null) as {ok?:boolean;message?:string}|null;setStatus(response.ok&&body?.ok?"Barber profile updated.":body?.message||"The barber profile could not be updated.");if(response.ok)router.refresh();setBusy(false)}
  return <section className="portal-card"><p className="text-[9px] tracking-[.18em] uppercase text-[var(--color-brass)]">Profile management</p><h2 className="font-display mt-2 text-2xl">Public and operational details</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label><span className="form-label">Display name</span><input className="form-control" value={name} onChange={(e)=>setName(e.target.value)}/></label><label><span className="form-label">Professional title</span><input className="form-control" value={title} onChange={(e)=>setTitle(e.target.value)}/></label><label className="md:col-span-2"><span className="form-label">Short introduction</span><textarea className="form-control min-h-24" value={intro} onChange={(e)=>setIntro(e.target.value)}/></label><label className="md:col-span-2"><span className="form-label">Biography</span><textarea className="form-control min-h-36" value={bio} onChange={(e)=>setBio(e.target.value)}/></label><label><span className="form-label">Specialties, one per line</span><textarea className="form-control min-h-28" value={specialties} onChange={(e)=>setSpecialties(e.target.value)}/></label><label><span className="form-label">Languages, comma separated</span><textarea className="form-control min-h-28" value={languages} onChange={(e)=>setLanguages(e.target.value)}/></label><label><span className="form-label">Profile status</span><select className="form-control" value={profileStatus} onChange={(e)=>setProfileStatus(e.target.value)}><option value="draft">Draft</option><option value="in_review">In review</option><option value="approved">Approved</option><option value="published">Published</option><option value="archived">Archived</option></select></label>{owner?<label><span className="form-label">Square team member ID</span><input className="form-control" value={squareId} onChange={(e)=>setSquareId(e.target.value)}/></label>:null}<label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={active} onChange={(e)=>setActive(e.target.checked)} disabled={!owner&&!active}/> Active access</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={featured} onChange={(e)=>setFeatured(e.target.checked)}/> Featured publicly</label><button type="button" disabled={busy} onClick={()=>void save()} className="w-fit rounded-full bg-[var(--color-brass)] px-5 py-3 text-[9px] tracking-[.16em] uppercase text-[var(--color-ink)] disabled:opacity-50">{busy?"Saving":"Save profile"}</button></div>{status?<p className="mt-4 text-xs text-[var(--color-bone-muted)]" role="status">{status}</p>:null}</section>;
}
