"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export function AdminMembershipPlanForm() {
  const router = useRouter(); const [open,setOpen]=useState(false); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [price,setPrice]=useState(""); const [interval,setInterval]=useState("month"); const [benefits,setBenefits]=useState(""); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(){setBusy(true);setStatus("Creating draft plan...");const response=await fetch("/api/admin/memberships",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,description,priceCents:price?Math.round(Number(price)*100):null,billingInterval:interval,benefits:benefits.split("\n").map((item)=>item.trim()).filter(Boolean)})});const body=await response.json().catch(()=>null) as {ok?:boolean;message?:string}|null;setStatus(response.ok&&body?.ok?"Draft plan created. Provider mapping is still required before publication.":body?.message||"The plan could not be created.");if(response.ok){setName("");setDescription("");setPrice("");setBenefits("");router.refresh();}setBusy(false)}
  return <section className="portal-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[9px] tracking-[.18em] uppercase text-[var(--color-brass)]">Versioned terms</p><h2 className="font-display mt-2 text-2xl">Membership plan builder</h2></div><button type="button" onClick={()=>setOpen((value)=>!value)} className="rounded-full bg-[var(--color-brass)] px-5 py-3 text-[9px] tracking-[.16em] uppercase text-[var(--color-ink)]">{open?"Close":"Create draft"}</button></div>{open?<div className="mt-5 grid gap-4 md:grid-cols-2"><label><span className="form-label">Plan name</span><input className="form-control" value={name} onChange={(event)=>setName(event.target.value)}/></label><label><span className="form-label">Price</span><input className="form-control" type="number" min="0" step="0.01" value={price} onChange={(event)=>setPrice(event.target.value)}/></label><label><span className="form-label">Billing interval</span><select className="form-control" value={interval} onChange={(event)=>setInterval(event.target.value)}><option value="month">Monthly</option><option value="quarter">Quarterly</option><option value="year">Yearly</option><option value="one_time">One time</option></select></label><label className="md:col-span-2"><span className="form-label">Description</span><textarea className="form-control min-h-24" value={description} onChange={(event)=>setDescription(event.target.value)}/></label><label className="md:col-span-2"><span className="form-label">Benefits, one per line</span><textarea className="form-control min-h-32" value={benefits} onChange={(event)=>setBenefits(event.target.value)}/></label><button type="button" disabled={busy||!name} onClick={()=>void submit()} className="w-fit rounded-full bg-[var(--color-brass)] px-5 py-3 text-[9px] tracking-[.16em] uppercase text-[var(--color-ink)] disabled:opacity-50">{busy?"Creating":"Create draft"}</button></div>:null}{status?<p className="mt-4 text-xs text-[var(--color-bone-muted)]" role="status">{status}</p>:null}</section>;
}
