import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Clock3 } from "lucide-react";
import { notFound } from "next/navigation";
import { findJournalPost, journalPosts } from "@/lib/content/site";
import { journalBodies } from "@/lib/content/platform";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return journalPosts.map((post)=>({slug:post.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const post=findJournalPost((await params).slug);if(!post)return{};return{title:post.title.en,description:post.excerpt.en,alternates:{canonical:`/journal/${post.slug}`},openGraph:{type:"article",title:post.title.en,description:post.excerpt.en}};}
export default async function ArticlePage({params}:Props){const slug=(await params).slug;const post=findJournalPost(slug);const body=journalBodies[slug];if(!post||!body)notFound();return <main className="mx-auto max-w-3xl px-6 py-20 sm:px-10"><Link href="/journal" className="inline-flex items-center gap-2 text-[10px] tracking-[.2em] uppercase text-[var(--color-brass)]"><ArrowLeft className="h-4 w-4"/> Journal</Link><p className="mt-10 text-[10px] tracking-[.28em] uppercase text-[var(--color-brass)]">{post.category}</p><h1 className="font-display mt-5 text-5xl leading-tight sm:text-7xl">{post.title.en}</h1><div className="mt-5 flex items-center gap-2 text-xs text-[var(--color-bone-muted)]"><Clock3 className="h-4 w-4"/>{post.readingMinutes} minute read · {post.publishedAt}</div><p className="font-display mt-10 text-2xl leading-relaxed italic text-[var(--color-bone)]/90">{body.heading.en}</p><div className="hairline my-10"/><article className="space-y-6 text-base leading-8 text-[var(--color-bone-muted)]">{body.paragraphs.map((paragraph)=><p key={paragraph.en}>{paragraph.en}</p>)}<section className="mt-10 border border-[var(--color-ink-line)] bg-[var(--color-ink-soft)]/65 p-7"><h2 className="font-display text-2xl text-[var(--color-bone)]">Practical takeaways</h2><ul className="mt-5 space-y-3">{body.takeaways.map((takeaway)=><li key={takeaway.en} className="flex gap-3"><span className="mt-3 h-1 w-1 shrink-0 rounded-full bg-[var(--color-brass)]"/>{takeaway.en}</li>)}</ul></section></article><Link href="/book" className="mt-10 inline-flex items-center gap-2 rounded-full bg-[var(--color-brass)] px-7 py-3.5 text-[10px] tracking-[.2em] uppercase text-[var(--color-ink)]">Reserve a consultation <ArrowUpRight className="h-4 w-4"/></Link></main>}
