import { NextRequest, NextResponse } from "next/server";
import { getManagedAppointment } from "@/lib/booking/manage";
import { ACTIVE_STATUSES, COMPLETED_STATUS, isHoldStatus } from "@/lib/booking/rules";
import { absoluteUrl, businessConfig } from "@/lib/config/business";
function esc(value:string){return value.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;");}
// A calendar entry says what the booking really is: a checkout that is not
// paid yet is tentative, and a cancelled or released booking is cancelled.
function calendarStatus(status:string){if((ACTIVE_STATUSES as readonly string[]).includes(status)||status===COMPLETED_STATUS)return "CONFIRMED";if(isHoldStatus(status))return "TENTATIVE";return "CANCELLED";}
function stamp(value:string){return new Date(value).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z");}
export async function GET(request:NextRequest,context:{params:Promise<{reference:string}>}){const {reference}=await context.params;const token=request.nextUrl.searchParams.get("token")??"";const managed=await getManagedAppointment(reference,token);if(!managed)return NextResponse.json({ok:false},{status:404});const {appointment,location}=managed;const address=[location?.address_line_1,location?.city,location?.region,location?.postal_code].filter(Boolean).join(", ");const manageUrl=absoluteUrl(`/booking/confirmation/${encodeURIComponent(reference)}?token=${encodeURIComponent(token)}`);const body=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Luxury Barber Lounge//Booking//EN","CALSCALE:GREGORIAN","METHOD:PUBLISH","BEGIN:VEVENT",`UID:${appointment.id}@theluxurybarberlounge.com`,`DTSTAMP:${stamp(new Date().toISOString())}`,`DTSTART:${stamp(appointment.starts_at)}`,`DTEND:${stamp(appointment.ends_at)}`,`SUMMARY:${esc(`${appointment.service_name_snapshot} at ${businessConfig.name}`)}`,`DESCRIPTION:${esc(`Barber: ${appointment.barber_name_snapshot}\nReference: ${appointment.public_reference}\nManage: ${manageUrl}\nPhone: ${businessConfig.phone}`)}`,`LOCATION:${esc(address)}`,`STATUS:${calendarStatus(String(appointment.status))}`,"END:VEVENT","END:VCALENDAR",""] .join("\r\n");return new NextResponse(body,{headers:{"Content-Type":"text/calendar; charset=utf-8","Content-Disposition":`attachment; filename="${reference}.ics"`,"Cache-Control":"private, no-store","Referrer-Policy":"no-referrer"}});}
