-- ============================================================================
-- 202608180020_attribution_chain_and_deposit_gate.sql
--
-- PART A is ADDITIVE and has ALREADY BEEN APPLIED to production
-- (project xdggtawvapftqgwifwqx) on 2026-08-18. It is reproduced here so the
-- repo migration history matches the live database. Re-running is a no-op.
--
-- PART B is ENFORCING. Do NOT apply it until the accompanying code deploy is
-- live on Vercel. Applying it first will cause live bookings to fail, because
-- the currently deployed code still writes status='confirmed' directly.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- PART A — additive (already applied)
-- ---------------------------------------------------------------------------

alter table public.booking_metadata
  add column if not exists appointment_id uuid references public.appointments(id) on delete cascade;

create unique index if not exists booking_metadata_appointment_id_key
  on public.booking_metadata(appointment_id)
  where appointment_id is not null;

create index if not exists booking_attributions_metadata_idx
  on public.booking_attributions(booking_metadata_id);

alter table public.appointments
  add column if not exists client_declared_status text
    check (client_declared_status in ('new','existing','unsure'));

comment on column public.appointments.client_declared_status is
  'Client self-declaration captured at booking. Immutable per appointment; basis for attribution and commission split.';


-- ---------------------------------------------------------------------------
-- PART B — enforcing. APPLY ONLY AFTER THE CODE DEPLOY IS LIVE.
-- ---------------------------------------------------------------------------

-- B1. Deposit gate.
-- An appointment requiring a deposit may not reach a booked state until that
-- deposit is paid. This is enforced in the database so it cannot be bypassed
-- by the admin UI, a direct API call, or a future code regression.
create or replace function public.enforce_deposit_before_confirmation()
returns trigger
language plpgsql
as $$
begin
  if new.status in ('confirmed','checked_in','assigned','in_service')
     and coalesce(new.deposit_required_cents, 0) > 0
     and coalesce(new.deposit_status, 'pending') <> 'paid'
  then
    raise exception
      'DEPOSIT_REQUIRED: appointment % cannot enter status "%" until the deposit is paid (required: % cents, current deposit_status: %)',
      new.public_reference, new.status, new.deposit_required_cents, new.deposit_status
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enforce_deposit_before_confirmation on public.appointments;
create trigger trg_enforce_deposit_before_confirmation
  before insert or update of status, deposit_status on public.appointments
  for each row execute function public.enforce_deposit_before_confirmation();


-- B2. Barbers may not claim clients who declared themselves NEW.
-- A client who states this is their first visit is shop-generated by
-- definition, so the 100%-to-barber path is closed for them entirely.
-- Enforced at the database layer, not in the portal UI.
create or replace function public.block_barber_claim_on_new_clients()
returns trigger
language plpgsql
as $$
declare
  declared text;
  appt_ref text;
begin
  select a.client_declared_status, a.public_reference
    into declared, appt_ref
  from public.booking_metadata bm
  join public.appointments a on a.id = bm.appointment_id
  where bm.id = new.booking_metadata_id;

  if declared = 'new' and new.attribution_type <> 'shop' then
    raise exception
      'CLAIM_BLOCKED_NEW_CLIENT: appointment % was booked by a client who declared themselves NEW; barber attribution is not permitted.',
      coalesce(appt_ref, '(unknown)')
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_block_barber_claim_on_new_clients on public.booking_attributions;
create trigger trg_block_barber_claim_on_new_clients
  before insert or update on public.booking_attributions
  for each row execute function public.block_barber_claim_on_new_clients();


-- B3. Same rule on the formal claims table, so a barber cannot open a dispute
-- against a new client and have an admin approve it by mistake.
create or replace function public.block_claim_submission_on_new_clients()
returns trigger
language plpgsql
as $$
declare
  declared text;
begin
  select a.client_declared_status into declared
  from public.appointments a
  where a.client_id = new.client_id
  order by a.created_at asc
  limit 1;

  if declared = 'new' then
    raise exception
      'CLAIM_BLOCKED_NEW_CLIENT: this client was acquired as a new shop client; pre-existing claims are not permitted.'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_block_claim_submission_on_new_clients on public.attribution_claims;
create trigger trg_block_claim_submission_on_new_clients
  before insert on public.attribution_claims
  for each row execute function public.block_claim_submission_on_new_clients();
